repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        files: ^backend/.*\.py$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^backend/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.13.2
    hooks:
      - id: isort
        files: ^backend/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.3.3"]
        files: |
          ^frontend/.*\.(js|jsx|ts|tsx|json|css|md|html|yml|yaml)$
