services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/data
    environment:
      - SECRET_KEY=your-production-secret-change-this
      - ALLOWED_ORIGINS=http://localhost:80,https://yourdomain.com
    networks:
      - app-network

volumes:
  backend-data:

networks:
  app-network:
    driver: bridge