version: "3.9"

services:
  backend:
    build: ./backend
    env_file: .env
    environment:
      # Ensure DATABASE path defaults inside container
      - DATABASE=/data/employee.db
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/data
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    env_file: .env
    ports:
      - "80:80"
      - "443:443"  # For future SSL support
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

  ddns:
    image: curlimages/curl:8.8.0
    env_file: .env
    command: ["sh", "-c", ": $${FREEDNS_UPDATE_INTERVAL:=300}; while true; do if [ -n \"$$FREEDNS_UPDATE_URL\" ]; then echo \"[DDNS] Updating at $$(date -u)\"; curl -fsS --max-time 20 \"$$FREEDNS_UPDATE_URL\" || echo \"[DDNS] update failed\"; else echo '[DDNS] FREEDNS_UPDATE_URL not set'; fi; sleep $$FREEDNS_UPDATE_INTERVAL; done"]
    restart: unless-stopped
    networks:
      - app-network

volumes:
  backend-data:

networks:
  app-network:
    driver: bridge